class GetDeviceError(Exception): ...


class CheckModuleError(Exception): ...


class ImplementChangeError(Exception): ...


class PreCheckError(Exception): ...


class ActivationError(Exception): ...


class CloseChangeError(Exception): ...


class CancelChangeError(Exception): ...


class UploadArtifactsError(Exception): ...


class CreateIncidentError(Exception): ...
